In [67]:
import pandas as pd
import numpy as np

In [68]:
df = pd.read_csv("diabetes.csv")

In [69]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               2000 non-null   int64
 1   Glucose                   2000 non-null   int64
 2   BloodPressure             2000 non-null   int64
 3   SkinThickness             2000 non-null   int64
 4   Insulin                   2000 non-null   int64
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64
 8   Outcome                   2000 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 140.8 KB

In [71]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [72]:
df.shape

(2000, 9)

In [73]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [74]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,0
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,0
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,0

In [78]:
df['Glucose'].unique()

array([138,  84, 145, 135, 139, 173,  99, 194,  83,  89, 125,  80, 166,
       110,  81, 195, 154, 117,   0,  94,  96,  75, 180, 130, 120,  91,
       163, 122, 103, 102,  90, 111, 133, 106, 171, 159, 146,  71, 105,
       101,  88, 176, 150,  73, 187, 100,  44, 141, 114, 109,  95, 126,
       129,  79,  62, 131, 112, 113,  74, 137, 136, 107, 123, 134, 142,
       144,  92,  93, 151,  85, 155,  76, 160, 124,  78,  97, 162, 132,
       118, 170, 128, 108,  57, 147, 156, 153, 188, 152, 104, 148,  87,
       179, 143, 119, 181, 158, 196, 184, 140, 177, 197, 164, 165,  86,
       193, 191, 161, 167,  77, 115, 182, 157, 178, 116,  61, 189,  98,
       127,  82,  72, 168, 172, 175,  68, 186, 198, 121,  67, 183, 174,
       199,  56, 169, 149,  65, 190])

In [79]:
df['BloodPressure'].unique()

array([ 62,  82,   0,  68,  78,  72,  80,  65,  90,  70,  74,  64,  60,
        50,  54,  76,  84,  92, 110,  66,  56,  88,  58,  85,  86,  75,
        48,  44, 108,  55,  96, 122,  30,  52,  98, 104,  95,  46, 102,
       100,  61,  94,  24,  38, 106, 114,  40])

In [80]:
df['SkinThickness'].unique()

array([ 35,  31,   0,  42,  41,  32,  17,  28,  30,  38,  18,  15,  33,
        19,  25,  39,  26,  23,  37,  47,  24,  27,  11,  21,  34,  10,
        60,  13,  20,  22,  29,  54,  40,  51,  56,  36,  14,  50,  44,
        12,  46,  16,   7,  52,  43,  45,  48,   8,  49,  63,  99,  59,
       110])

In [81]:
df['Insulin'].unique()

array([  0, 125, 250, 480, 265,  66, 122,  76, 145, 193,  71,  79,  90,
       170, 210,  86, 105, 192, 207,  70, 240,  82,  36,  23, 300, 342,
       304, 110, 142, 128,  38, 100, 140, 270, 176,  48,  64, 228, 220,
        40, 152,  18, 135, 495,  37, 175,  51,  99,  94, 168, 225,  49,
        50,  92, 325,  63, 284, 119, 204, 155, 485,  53, 114, 285, 156,
        78, 130,  55,  58, 160, 318,  44, 190, 280,  87, 271, 129, 120,
       478,  56,  32, 744, 370,  45,  88, 194, 680, 402, 258, 375, 150,
        67,  57, 116, 278, 545,  75,  74, 182, 360, 215, 184,  42, 132,
       148, 180, 205,  96,  85, 231,  29,  68,  52, 255, 171,  73, 108,
        83,  43, 167,  54, 249, 293, 465,  89, 158,  84,  72,  59,  81,
       196, 415, 275, 115, 165, 579, 310,  61, 474, 277,  60,  14,  95,
       237, 191, 328, 326, 188, 106,  65, 166, 274,  77, 126, 330, 600,
       230, 185,  25,  41, 272, 321, 144,  15, 183,  91,  46, 440, 159,
       540, 200, 335, 387,  22, 291, 392, 178, 127, 510,  16, 112, 177])

In [82]:
df['BMI'].unique()

array([33.6, 38.2, 44.2, 42.3, 40.7, 46.5, 25.6, 26.1, 36.8, 33.5, 32.8,
       28.9,  0. , 26.6, 26. , 30.1, 25.1, 29.3, 25.2, 37.2, 39. , 33.3,
       37.3, 36.5, 28.6, 30.4, 25. , 29.7, 22.1, 24.2, 27.3, 31.6, 27.6,
       24. , 33.2, 32.9, 37.1, 34. , 40.2, 22.7, 45.4, 27.4, 42. , 28. ,
       39.1, 19.4, 24.4, 33.7, 34.7, 23. , 37.7, 46.8, 40.5, 41.5, 25.4,
       29. , 32.5, 42.7, 19.6, 43.4, 35.1, 32. , 24.7, 32.6, 43.2, 22.4,
       24.6, 48.8, 32.4, 36.6, 38.5, 26.5, 19.1, 46.7, 23.8, 33.9, 20.4,
       28.7, 49.7, 22.5, 39.6, 29.5, 34.3, 37.4, 31.2, 30.5, 28.2, 23.2,
       53.2, 34.2, 26.8, 55. , 42.9, 34.5, 27.9, 38.3, 21.1, 33.8, 30.8,
       36.9, 39.5, 21.9, 40.6, 47.9, 50. , 40.9, 29.9, 29.6, 31.9, 28.4,
       35.4, 43.5, 32.7, 67.1, 45. , 34.9, 27.7, 35.9, 22.6, 33.1, 52.3,
       39.4, 24.3, 22.9, 34.8, 30.9, 31. , 40.1, 23.9, 37.5, 35.5, 42.8,
       42.6, 41.8, 35.8, 30. , 37.8, 34.6, 28.8, 23.6, 35.7, 36.7, 45.2,
       44. , 46.2, 35. , 43.6, 44.1, 18.4, 29.2, 27.1, 25.9, 32.1, 36.3,
       40. , 27.5, 45.6, 27.8, 24.9, 25.3, 37.9, 27. , 38.7, 20.8, 36.1,
       43.3, 30.7, 32.3, 52.9, 21. , 39.7, 25.5, 24.8, 26.2, 34.1, 19.3,
       38.1, 23.5, 45.5, 23.1, 39.9, 21.8, 41. , 42.2, 34.4, 27.2, 35.3,
       29.8, 39.2, 38.4, 36.2, 48.3, 20. , 22.3, 45.7, 23.7, 42.1, 42.4,
       18.2, 26.4, 45.3, 37. , 22.2, 24.5, 32.2, 59.4, 21.2, 26.7, 30.2,
       37.6, 46.1, 41.3, 38.8, 35.2, 30.3, 26.3, 21.7, 36.4, 28.5, 26.9,
       38.6, 31.3, 19.5, 25.8, 20.1, 40.8, 23.4, 28.3, 38.9, 57.3, 35.6,
       36. , 49.6, 44.6, 24.1, 44.5, 39.8, 38. , 41.2, 23.3, 49.3, 46.3,
       80.6, 64.4, 50.7, 52.7, 48.7])

In [83]:
df['Age'].unique()

array([47, 23, 31, 24, 21, 58, 28, 67, 42, 33, 45, 22, 66, 30, 25, 55, 39,
       41, 40, 38, 35, 64, 46, 27, 56, 26, 37, 48, 54, 29, 44, 36, 32, 43,
       34, 60, 61, 69, 62, 65, 57, 52, 51, 49, 63, 59, 72, 81, 50, 53, 70,
       68])

In [84]:
df['DiabetesPedigreeFunction'].unique()

array([0.127, 0.233, 0.63 , 0.365, 0.536, 1.159, 0.294, 0.551, 0.629,
       0.292, 0.145, 1.144, 0.174, 0.304, 0.547, 0.163, 0.839, 0.313,
       0.267, 0.727, 0.738, 0.238, 0.263, 0.314, 0.692, 0.968, 0.409,
       0.297, 0.207, 0.2  , 0.525, 0.154, 0.268, 0.512, 0.966, 0.42 ,
       0.665, 0.503, 1.39 , 0.271, 0.696, 0.235, 0.721, 1.893, 0.564,
       0.586, 0.344, 0.305, 0.491, 0.526, 0.342, 0.467, 0.718, 0.248,
       0.254, 0.962, 1.781, 0.173, 0.27 , 0.587, 0.699, 0.258, 0.203,
       0.855, 0.845, 0.334, 0.189, 0.867, 0.411, 0.583, 0.231, 0.396,
       0.14 , 0.391, 0.37 , 0.307, 0.102, 0.767, 0.237, 0.227, 0.698,
       0.178, 0.324, 0.153, 0.165, 0.443, 0.261, 0.277, 0.761, 0.255,
       0.13 , 0.323, 0.356, 0.325, 1.222, 0.179, 0.262, 0.283, 0.93 ,
       0.801, 0.287, 0.336, 0.247, 0.199, 0.543, 0.192, 0.588, 0.539,
       0.22 , 0.654, 0.223, 0.759, 0.26 , 0.404, 0.186, 0.278, 0.496,
       0.452, 0.403, 0.741, 0.361, 1.114, 0.457, 0.647, 0.088, 0.597,
       0.532, 0.703, 0.159, 0.286, 0.318, 0.272, 0.572, 0.096, 1.4  ,
       0.218, 0.085, 0.399, 0.432, 1.189, 0.687, 0.137, 0.337, 0.637,
       0.833, 0.229, 0.817, 0.204, 0.167, 0.368, 0.743, 0.722, 0.256,
       0.709, 0.471, 0.495, 0.18 , 0.542, 0.773, 0.678, 0.719, 0.382,
       0.319, 0.19 , 0.956, 0.084, 0.725, 0.299, 0.244, 0.745, 0.615,
       1.321, 0.64 , 0.142, 0.374, 0.383, 0.578, 0.136, 0.395, 0.187,
       0.905, 0.15 , 0.874, 0.236, 0.787, 0.407, 0.605, 0.151, 0.289,
       0.355, 0.29 , 0.375, 0.164, 0.431, 0.742, 0.514, 0.464, 1.224,
       1.072, 0.805, 0.209, 0.666, 0.101, 0.198, 0.652, 2.329, 0.089,
       0.645, 0.394, 0.293, 0.479, 0.686, 0.831, 0.582, 0.446, 0.402,
       1.318, 0.329, 1.213, 0.427, 0.282, 0.143, 0.38 , 0.284, 0.249,
       0.926, 0.557, 0.092, 0.655, 1.353, 0.612, 0.226, 0.997, 0.933,
       1.101, 0.078, 0.24 , 1.136, 0.128, 0.422, 0.251, 0.677, 0.296,
       0.454, 0.744, 0.881, 0.28 , 0.259, 0.619, 0.808, 0.34 , 0.434,
       0.757, 0.613, 0.52 , 0.412, 0.84 , 0.156, 0.215, 0.326, 1.391,
       0.875, 0.433, 0.626, 1.127, 0.315, 0.345, 0.129, 0.527, 0.197,
       0.731, 0.148, 0.123, 0.122, 1.476, 0.166, 0.932, 0.343, 0.893,
       0.331, 0.472, 0.673, 0.389, 0.485, 0.349, 0.279, 0.346, 0.252,
       0.243, 0.58 , 0.559, 0.302, 0.569, 0.378, 0.385, 0.499, 0.306,
       0.234, 2.137, 1.731, 0.545, 0.225, 0.816, 0.528, 0.509, 1.021,
       0.821, 0.947, 1.268, 0.221, 0.205, 0.66 , 0.239, 0.949, 0.444,
       0.463, 0.803, 1.6  , 0.944, 0.196, 0.241, 0.161, 0.135, 0.376,
       1.191, 0.702, 0.674, 1.076, 0.534, 1.095, 0.554, 0.624, 0.219,
       0.507, 0.561, 0.421, 0.516, 0.264, 0.328, 0.108, 1.138, 0.147,
       0.435, 0.497, 0.23 , 0.955, 2.42 , 0.658, 0.33 , 0.51 , 0.285,
       0.415, 0.381, 0.832, 0.498, 0.212, 0.364, 1.001, 0.46 , 0.733,
       0.416, 0.705, 1.022, 0.269, 0.6  , 0.183, 0.571, 0.607, 0.17 ,
       0.21 , 0.126, 0.711, 0.466, 0.162, 0.419, 0.771, 0.107, 0.493,
       0.717, 0.917, 0.501, 1.251, 0.735, 0.804, 0.661, 0.549, 0.825,
       0.423, 1.034, 0.16 , 0.341, 0.68 , 0.591, 0.3  , 0.121, 0.502,
       0.401, 0.601, 0.748, 0.338, 0.43 , 0.892, 0.813, 0.693, 0.245,
       0.575, 0.371, 0.206, 0.417, 1.154, 0.925, 0.175, 1.699, 0.682,
       0.194, 0.4  , 0.1  , 1.258, 0.482, 0.138, 0.593, 0.878, 0.157,
       0.257, 1.282, 0.141, 0.246, 1.698, 1.461, 0.347, 0.158, 0.362,
       0.393, 0.144, 0.732, 0.115, 0.465, 0.649, 0.871, 0.149, 0.695,
       0.303, 0.61 , 0.73 , 0.134, 0.447, 0.455, 0.133, 0.155, 1.162,
       1.292, 0.182, 1.394, 0.217, 0.631, 0.88 , 0.614, 0.332, 0.366,
       0.181, 0.828, 0.335, 0.856, 0.886, 0.439, 0.191, 0.253, 0.598,
       0.904, 0.483, 0.565, 0.118, 0.177, 0.176, 0.295, 0.441, 0.352,
       0.826, 0.97 , 0.595, 0.317, 0.265, 0.646, 0.426, 0.56 , 0.515,
       0.453, 0.785, 0.734, 1.174, 0.488, 0.358, 1.096, 0.408, 1.182,
       0.222, 1.057, 0.766, 0.171, 0.82 , 0.72 , 0.62 , 0.152, 0.322,
       0.32 ])

In [85]:
columns_with_zero= ['Glucose', 'BloodPressure','SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

In [86]:
for col in columns_with_zero:
    df[col]= df[col].replace(0, np.nan)

In [87]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138.0,62.0,35.0,NaN,33.6,0.127,47,1
1,0,84.0,82.0,31.0,125.0,38.2,0.233,23,0
2,0,145.0,NaN,NaN,NaN,44.2,0.630,31,1
3,0,135.0,68.0,42.0,250.0,42.3,0.365,24,1
4,1,139.0,62.0,41.0,480.0,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75.0,64.0,24.0,55.0,29.7,0.370,33,0
1996,8,179.0,72.0,42.0,130.0,32.7,0.719,36,1
1997,6,85.0,78.0,NaN,NaN,31.2,0.382,42,0
1998,0,129.0,110.0,46.0,130.0,67.1,0.319,26,1
1999,2,81.0,72.0,15.0,76.0,30.1,0.547,25,0

In [88]:
df.isna().sum()

Pregnancies                   0
Glucose                      13
BloodPressure                90
SkinThickness               573
Insulin                     956
BMI                          28
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [89]:
for col in columns_with_zero:
    df[col] = df[col].fillna(df[col].median())

In [90]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
X= df.drop('Outcome', axis= 1)
y= df['Outcome']

In [93]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2,138.0,62.0,35.0,126.0,33.6,0.127,47
1,0,84.0,82.0,31.0,125.0,38.2,0.233,23
2,0,145.0,72.0,29.0,126.0,44.2,0.630,31
3,0,135.0,68.0,42.0,250.0,42.3,0.365,24
4,1,139.0,62.0,41.0,480.0,40.7,0.536,21
...,...,...,...,...,...,...,...,...
1995,2,75.0,64.0,24.0,55.0,29.7,0.370,33
1996,8,179.0,72.0,42.0,130.0,32.7,0.719,36
1997,6,85.0,78.0,29.0,126.0,31.2,0.382,42
1998,0,129.0,110.0,46.0,130.0,67.1,0.319,26
1999,2,81.0,72.0,15.0,76.0,30.1,0.547,25

In [94]:
y

0       1
1       0
2       1
3       1
4       0
       ..
1995    0
1996    1
1997    0
1998    1
1999    0
Name: Outcome, Length: 2000, dtype: int64

In [97]:
print(X.columns)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='str')

In [98]:
 X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2, random_state= 20)

In [99]:
print(X.shape, X_train.shape, X_test.shape)

(2000, 8) (1600, 8) (400, 8)

In [100]:
print(y.shape, y_train.shape, y_test.shape)

(2000,) (1600,) (400,)

In [101]:
from sklearn.linear_model import LogisticRegression

In [102]:
model = LogisticRegression()

In [103]:
model.fit(X_train, y_train)

C:\Users\mohdr\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [104]:
from sklearn.metrics import accuracy_score

In [105]:
y_pred = model.predict(X_test)

In [106]:
acc= accuracy_score(y_test, y_pred)

In [107]:
acc

0.7475

In [109]:
model.predict([[4,132.0,63.0,31.0,122.0,32.6,0.127,57]])

C:\Users\mohdr\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [110]:
import pickle

In [111]:
pickle.dump(model, open('diabetes_pred.pkl', 'wb'))