In [1]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

# Load dataset
data = load_breast_cancer()

In [2]:
X = pd.DataFrame(data.data, columns=data.feature_names)

In [3]:
y = data.target

In [4]:
X.shape

(569, 30)

In [5]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

1. Variance Threshold

In [7]:
from sklearn.feature_selection import VarianceThreshold

selector= VarianceThreshold(threshold= 0.1)
X_new = selector.fit_transform(X)

print("New :",X_new.shape)
print("Old :" ,X.shape)

New : (569, 11)
Old : (569, 30)

In [8]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [9]:
selected = X.columns[selector.get_support()]

print(selected)

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'texture error', 'perimeter error', 'area error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area'],
      dtype='str')

In [10]:
X_new = pd.DataFrame(X_new, columns=selected)

X_new.head()

,mean radius,mean texture,mean perimeter,mean area,texture error,perimeter error,area error,worst radius,worst texture,worst perimeter,worst area
0,17.99,10.38,122.80,1001.0,0.9053,8.589,153.40,25.38,17.33,184.60,2019.0
1,20.57,17.77,132.90,1326.0,0.7339,3.398,74.08,24.99,23.41,158.80,1956.0
2,19.69,21.25,130.00,1203.0,0.7869,4.585,94.03,23.57,25.53,152.50,1709.0
3,11.42,20.38,77.58,386.1,1.1560,3.445,27.23,14.91,26.50,98.87,567.7
4,20.29,14.34,135.10,1297.0,0.7813,5.438,94.44,22.54,16.67,152.20,1575.0

2- Correlation Method

In [11]:
data = load_breast_cancer()

In [12]:
print(data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [13]:
X= pd.DataFrame(data.data, columns= data.feature_names)

y= data.target

In [14]:
df = X.copy()

df["target"] = y

In [15]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [16]:
print(df.shape)

(569, 31)

In [17]:
corr_matrix = df.corr()
print(corr_matrix)

                         mean radius  mean texture  mean perimeter  mean area  \
mean radius                 1.000000      0.323782        0.997855   0.987357
mean texture                0.323782      1.000000        0.329533   0.321086
mean perimeter              0.997855      0.329533        1.000000   0.986507
mean area                   0.987357      0.321086        0.986507   1.000000
mean smoothness             0.170581     -0.023389        0.207278   0.177028
mean compactness            0.506124      0.236702        0.556936   0.498502
mean concavity              0.676764      0.302418        0.716136   0.685983
mean concave points         0.822529      0.293464        0.850977   0.823269
mean symmetry               0.147741      0.071401        0.183027   0.151293
mean fractal dimension     -0.311631     -0.076437       -0.261477  -0.283110
radius error                0.679090      0.275869        0.691765   0.732562
texture error              -0.097317      0.386358       -0.086761  -0.066280
perimeter error             0.674172      0.281673        0.693135   0.726628
area error                  0.735864      0.259845        0.744983   0.800086
smoothness error           -0.222600      0.006614       -0.202694  -0.166777
compactness error           0.206000      0.191975        0.250744   0.212583
concavity error             0.194204      0.143293        0.228082   0.207660
concave points error        0.376169      0.163851        0.407217   0.372320
symmetry error             -0.104321      0.009127       -0.081629  -0.072497
fractal dimension error    -0.042641      0.054458       -0.005523  -0.019887
worst radius                0.969539      0.352573        0.969476   0.962746
worst texture               0.297008      0.912045        0.303038   0.287489
worst perimeter             0.965137      0.358040        0.970387   0.959120
worst area                  0.941082      0.343546        0.941550   0.959213
worst smoothness            0.119616      0.077503        0.150549   0.123523
worst compactness           0.413463      0.277830        0.455774   0.390410
worst concavity             0.526911      0.301025        0.563879   0.512606
worst concave points        0.744214      0.295316        0.771241   0.722017
worst symmetry              0.163953      0.105008        0.189115   0.143570
worst fractal dimension     0.007066      0.119205        0.051019   0.003738
target                     -0.730029     -0.415185       -0.742636  -0.708984

                         mean smoothness  mean compactness  mean concavity  \
mean radius                     0.170581          0.506124        0.676764
mean texture                   -0.023389          0.236702        0.302418
mean perimeter                  0.207278          0.556936        0.716136
mean area                       0.177028          0.498502        0.685983
mean smoothness                 1.000000          0.659123        0.521984
mean compactness                0.659123          1.000000        0.883121
mean concavity                  0.521984          0.883121        1.000000
mean concave points             0.553695          0.831135        0.921391
mean symmetry                   0.557775          0.602641        0.500667
mean fractal dimension          0.584792          0.565369        0.336783
radius error                    0.301467          0.497473        0.631925
texture error                   0.068406          0.046205        0.076218
perimeter error                 0.296092          0.548905        0.660391
area error                      0.246552          0.455653        0.617427
smoothness error                0.332375          0.135299        0.098564
compactness error               0.318943          0.738722        0.670279
concavity error                 0.248396          0.570517        0.691270
concave points error            0.380676          0.642262        0.683260
symmetry error                  0.200774          0.229977        0.178009
fractal dimension error         0.283607          0.507318        0.449301
worst radius                    0.213120          0.535315        0.688236
worst texture                   0.036072          0.248133        0.299879
worst perimeter                 0.238853          0.590210        0.729565
worst area                      0.206718          0.509604        0.675987
worst smoothness                0.805324          0.565541        0.448822
worst compactness               0.472468          0.865809        0.754968
worst concavity                 0.434926          0.816275        0.884103
worst concave points            0.503053          0.815573        0.861323
worst symmetry                  0.394309          0.510223        0.409464
worst fractal dimension         0.499316          0.687382        0.514930
target                         -0.358560         -0.596534       -0.696360

                         mean concave points  mean symmetry  \
mean radius                         0.822529       0.147741
mean texture                        0.293464       0.071401
mean perimeter                      0.850977       0.183027
mean area                           0.823269       0.151293
mean smoothness                     0.553695       0.557775
mean compactness                    0.831135       0.602641
mean concavity                      0.921391       0.500667
mean concave points                 1.000000       0.462497
mean symmetry                       0.462497       1.000000
mean fractal dimension              0.166917       0.479921
radius error                        0.698050       0.303379
texture error                       0.021480       0.128053
perimeter error                     0.710650       0.313893
area error                          0.690299       0.223970
smoothness error                    0.027653       0.187321
compactness error                   0.490424       0.421659
concavity error                     0.439167       0.342627
concave points error                0.615634       0.393298
symmetry error                      0.095351       0.449137
fractal dimension error             0.257584       0.331786
worst radius                        0.830318       0.185728
worst texture                       0.292752       0.090651
worst perimeter                     0.855923       0.219169
worst area                          0.809630       0.177193
worst smoothness                    0.452753       0.426675
worst compactness                   0.667454       0.473200
worst concavity                     0.752399       0.433721
worst concave points                0.910155       0.430297
worst symmetry                      0.375744       0.699826
worst fractal dimension             0.368661       0.438413
target                             -0.776614      -0.330499

                         mean fractal dimension  ...  worst texture  \
mean radius                           -0.311631  ...       0.297008
mean texture                          -0.076437  ...       0.912045
mean perimeter                        -0.261477  ...       0.303038
mean area                             -0.283110  ...       0.287489
mean smoothness                        0.584792  ...       0.036072
mean compactness                       0.565369  ...       0.248133
mean concavity                         0.336783  ...       0.299879
mean concave points                    0.166917  ...       0.292752
mean symmetry                          0.479921  ...       0.090651
mean fractal dimension                 1.000000  ...      -0.051269
radius error                           0.000111  ...       0.194799
texture error                          0.164174  ...       0.409003
perimeter error                        0.039830  ...       0.200371
area error                            -0.090170  ...       0.196497
smoothness error                       0.401964  ...      -0.074743
compactness error                      0.559837  ...       0.143003
concavity error                        0.446630  ...       0.100241
concave points error                   0.341198  ...       0.086741
symmetry error                         0.345007  ...      -0.077473
fractal dimension error                0.688132  ...      -0.003195
worst radius                          -0.253691  ...       0.359921
worst texture                         -0.051269  ...       1.000000
worst perimeter                       -0.205151  ...       0.365098
worst area                            -0.231854  ...       0.345842
worst smoothness                       0.504942  ...       0.225429
worst compactness                      0.458798  ...       0.360832
worst concavity                        0.346234  ...       0.368366
worst concave points                   0.175325  ...       0.359755
worst symmetry                         0.334019  ...       0.233027
worst fractal dimension                0.767297  ...       0.219122
target                                 0.012838  ...      -0.456903

                         worst perimeter  worst area  worst smoothness  \
mean radius                     0.965137    0.941082          0.119616
mean texture                    0.358040    0.343546          0.077503
mean perimeter                  0.970387    0.941550          0.150549
mean area                       0.959120    0.959213          0.123523
mean smoothness                 0.238853    0.206718          0.805324
mean compactness                0.590210    0.509604          0.565541
mean concavity                  0.729565    0.675987          0.448822
mean concave points             0.855923    0.809630          0.452753
mean symmetry                   0.219169    0.177193          0.426675
mean fractal dimension         -0.205151   -0.231854          0.504942
radius error                    0.719684    0.751548          0.141919
texture error                  -0.102242   -0.083195         -0.073658
perimeter error                 0.721031    0.730713          0.130054
area error                      0.761213    0.811408          0.125389
smoothness error               -0.217304   -0.182195          0.314457
compactness error               0.260516    0.199371          0.227394
concavity error                 0.226680    0.188353          0.168481
concave points error            0.394999    0.342271          0.215351
symmetry error                 -0.103753   -0.110343         -0.012662
fractal dimension error        -0.001000   -0.022736          0.170568
worst radius                    0.993708    0.984015          0.216574
worst texture                   0.365098    0.345842          0.225429
worst perimeter                 1.000000    0.977578          0.236775
worst area                      0.977578    1.000000          0.209145
worst smoothness                0.236775    0.209145          1.000000
worst compactness               0.529408    0.438296          0.568187
worst concavity                 0.618344    0.543331          0.518523
worst concave points            0.816322    0.747419          0.547691
worst symmetry                  0.269493    0.209146          0.493838
worst fractal dimension         0.138957    0.079647          0.617624
target                         -0.782914   -0.733825         -0.421465

                         worst compactness  worst concavity  \
mean radius                       0.413463         0.526911
mean texture                      0.277830         0.301025
mean perimeter                    0.455774         0.563879
mean area                         0.390410         0.512606
mean smoothness                   0.472468         0.434926
mean compactness                  0.865809         0.816275
mean concavity                    0.754968         0.884103
mean concave points               0.667454         0.752399
mean symmetry                     0.473200         0.433721
mean fractal dimension            0.458798         0.346234
radius error                      0.287103         0.380585
texture error                    -0.092439        -0.068956
perimeter error                   0.341919         0.418899
area error                        0.283257         0.385100
smoothness error                 -0.055558        -0.058298
compactness error                 0.678780         0.639147
concavity error                   0.484858         0.662564
concave points error              0.452888         0.549592
symmetry error                    0.060255         0.037119
fractal dimension error           0.390159         0.379975
worst radius                      0.475820         0.573975
worst texture                     0.360832         0.368366
worst perimeter                   0.529408         0.618344
worst area                        0.438296         0.543331
worst smoothness                  0.568187         0.518523
worst compactness                 1.000000         0.892261
worst concavity                   0.892261         1.000000
worst concave points              0.801080         0.855434
worst symmetry                    0.614441         0.532520
worst fractal dimension           0.810455         0.686511
target                           -0.590998        -0.659610

                         worst concave points  worst symmetry  \
mean radius                          0.744214        0.163953
mean texture                         0.295316        0.105008
mean perimeter                       0.771241        0.189115
mean area                            0.722017        0.143570
mean smoothness                      0.503053        0.394309
mean compactness                     0.815573        0.510223
mean concavity                       0.861323        0.409464
mean concave points                  0.910155        0.375744
mean symmetry                        0.430297        0.699826
mean fractal dimension               0.175325        0.334019
radius error                         0.531062        0.094543
texture error                       -0.119638       -0.128215
perimeter error                      0.554897        0.109930
area error                           0.538166        0.074126
smoothness error                    -0.102007       -0.107342
compactness error                    0.483208        0.277878
concavity error                      0.440472        0.197788
concave points error                 0.602450        0.143116
symmetry error                      -0.030413        0.389402
fractal dimension error              0.215204        0.111094
worst radius                         0.787424        0.243529
worst texture                        0.359755        0.233027
worst perimeter                      0.816322        0.269493
worst area                           0.747419        0.209146
worst smoothness                     0.547691        0.493838
worst compactness                    0.801080        0.614441
worst concavity                      0.855434        0.532520
worst concave points                 1.000000        0.502528
worst symmetry                       0.502528        1.000000
worst fractal dimension              0.511114        0.537848
target                              -0.793566       -0.416294

                         worst fractal dimension    target
mean radius                             0.007066 -0.730029
mean texture                            0.119205 -0.415185
mean perimeter                          0.051019 -0.742636
mean area                               0.003738 -0.708984
mean smoothness                         0.499316 -0.358560
mean compactness                        0.687382 -0.596534
mean concavity                          0.514930 -0.696360
mean concave points                     0.368661 -0.776614
mean symmetry                           0.438413 -0.330499
mean fractal dimension                  0.767297  0.012838
radius error                            0.049559 -0.567134
texture error                          -0.045655  0.008303
perimeter error                         0.085433 -0.556141
area error                              0.017539 -0.548236
smoothness error                        0.101480  0.067016
compactness error                       0.590973 -0.292999
concavity error                         0.439329 -0.253730
concave points error                    0.310655 -0.408042
symmetry error                          0.078079  0.006522
fractal dimension error                 0.591328 -0.077972
worst radius                            0.093492 -0.776454
worst texture                           0.219122 -0.456903
worst perimeter                         0.138957 -0.782914
worst area                              0.079647 -0.733825
worst smoothness                        0.617624 -0.421465
worst compactness                       0.810455 -0.590998
worst concavity                         0.686511 -0.659610
worst concave points                    0.511114 -0.793566
worst symmetry                          0.537848 -0.416294
worst fractal dimension                 1.000000 -0.323872
target                                 -0.323872  1.000000

[31 rows x 31 columns]

In [18]:
target_corr= corr_matrix['target']

In [19]:
target_corr

mean radius               -0.730029
mean texture              -0.415185
mean perimeter            -0.742636
mean area                 -0.708984
mean smoothness           -0.358560
mean compactness          -0.596534
mean concavity            -0.696360
mean concave points       -0.776614
mean symmetry             -0.330499
mean fractal dimension     0.012838
radius error              -0.567134
texture error              0.008303
perimeter error           -0.556141
area error                -0.548236
smoothness error           0.067016
compactness error         -0.292999
concavity error           -0.253730
concave points error      -0.408042
symmetry error             0.006522
fractal dimension error   -0.077972
worst radius              -0.776454
worst texture             -0.456903
worst perimeter           -0.782914
worst area                -0.733825
worst smoothness          -0.421465
worst compactness         -0.590998
worst concavity           -0.659610
worst concave points      -0.793566
worst symmetry            -0.416294
worst fractal dimension   -0.323872
target                     1.000000
Name: target, dtype: float64

In [20]:
target_corr = target_corr.sort_values(
    ascending=False
)

print(target_corr)

target                     1.000000
smoothness error           0.067016
mean fractal dimension     0.012838
texture error              0.008303
symmetry error             0.006522
fractal dimension error   -0.077972
concavity error           -0.253730
compactness error         -0.292999
worst fractal dimension   -0.323872
mean symmetry             -0.330499
mean smoothness           -0.358560
concave points error      -0.408042
mean texture              -0.415185
worst symmetry            -0.416294
worst smoothness          -0.421465
worst texture             -0.456903
area error                -0.548236
perimeter error           -0.556141
radius error              -0.567134
worst compactness         -0.590998
mean compactness          -0.596534
worst concavity           -0.659610
mean concavity            -0.696360
mean area                 -0.708984
mean radius               -0.730029
worst area                -0.733825
mean perimeter            -0.742636
worst radius              -0.776454
mean concave points       -0.776614
worst perimeter           -0.782914
worst concave points      -0.793566
Name: target, dtype: float64

In [21]:
target_corr = target_corr.drop("target")

In [22]:
selected_features= target_corr[abs(target_corr)>0.5]

In [23]:
print(selected_features)

area error             -0.548236
perimeter error        -0.556141
radius error           -0.567134
worst compactness      -0.590998
mean compactness       -0.596534
worst concavity        -0.659610
mean concavity         -0.696360
mean area              -0.708984
mean radius            -0.730029
worst area             -0.733825
mean perimeter         -0.742636
worst radius           -0.776454
mean concave points    -0.776614
worst perimeter        -0.782914
worst concave points   -0.793566
Name: target, dtype: float64

In [24]:
selected_columns = selected_features.index

print(selected_columns)

Index(['area error', 'perimeter error', 'radius error', 'worst compactness',
       'mean compactness', 'worst concavity', 'mean concavity', 'mean area',
       'mean radius', 'worst area', 'mean perimeter', 'worst radius',
       'mean concave points', 'worst perimeter', 'worst concave points'],
      dtype='str')

In [25]:
X_selected = X[selected_columns]

In [26]:
X_selected.head()

,area error,perimeter error,radius error,worst compactness,mean compactness,worst concavity,mean concavity,mean area,mean radius,worst area,mean perimeter,worst radius,mean concave points,worst perimeter,worst concave points
0,153.40,8.589,1.0950,0.6656,0.27760,0.7119,0.3001,1001.0,17.99,2019.0,122.80,25.38,0.14710,184.60,0.2654
1,74.08,3.398,0.5435,0.1866,0.07864,0.2416,0.0869,1326.0,20.57,1956.0,132.90,24.99,0.07017,158.80,0.1860
2,94.03,4.585,0.7456,0.4245,0.15990,0.4504,0.1974,1203.0,19.69,1709.0,130.00,23.57,0.12790,152.50,0.2430
3,27.23,3.445,0.4956,0.8663,0.28390,0.6869,0.2414,386.1,11.42,567.7,77.58,14.91,0.10520,98.87,0.2575
4,94.44,5.438,0.7572,0.2050,0.13280,0.4000,0.1980,1297.0,20.29,1575.0,135.10,22.54,0.10430,152.20,0.1625

3. Chi-Square

In [27]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [28]:
data = load_breast_cancer()

In [29]:
X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = data.target

In [30]:
print(X.shape)

(569, 30)

In [31]:
selector = SelectKBest(
    score_func=chi2,
    k=10
)

# Selecting 10 best features

In [32]:
X_new = selector.fit_transform(X, y)

In [33]:
print(X_new.shape)

(569, 10)

In [34]:
selected_columns = X.columns[
    selector.get_support()
]

print(selected_columns)

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'perimeter error', 'area error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area'],
      dtype='str')

In [35]:
X_new = pd.DataFrame(
    X_new,
    columns=selected_columns
)

In [36]:
scores = selector.scores_

print(scores)

[2.66104917e+02 9.38975081e+01 2.01110286e+03 5.39916559e+04
 1.49899264e-01 5.40307549e+00 1.97123536e+01 1.05440354e+01
 2.57379775e-01 7.43065536e-05 3.46752472e+01 9.79353970e-03
 2.50571896e+02 8.75850471e+03 3.26620664e-03 6.13785332e-01
 1.04471761e+00 3.05231563e-01 8.03633831e-05 6.37136566e-03
 4.91689157e+02 1.74449400e+02 3.66503542e+03 1.12598432e+05
 3.97365694e-01 1.93149220e+01 3.95169151e+01 1.34854195e+01
 1.29886140e+00 2.31522407e-01]

In [37]:
feature_scores = pd.DataFrame({
    "Feature": X.columns,
    "Chi2 Score": selector.scores_
})

print(feature_scores)

                    Feature     Chi2 Score
0               mean radius     266.104917
1              mean texture      93.897508
2            mean perimeter    2011.102864
3                 mean area   53991.655924
4           mean smoothness       0.149899
5          mean compactness       5.403075
6            mean concavity      19.712354
7       mean concave points      10.544035
8             mean symmetry       0.257380
9    mean fractal dimension       0.000074
10             radius error      34.675247
11            texture error       0.009794
12          perimeter error     250.571896
13               area error    8758.504705
14         smoothness error       0.003266
15        compactness error       0.613785
16          concavity error       1.044718
17     concave points error       0.305232
18           symmetry error       0.000080
19  fractal dimension error       0.006371
20             worst radius     491.689157
21            worst texture     174.449400
22          worst perimeter    3665.035416
23               worst area  112598.431564
24         worst smoothness       0.397366
25        worst compactness      19.314922
26          worst concavity      39.516915
27     worst concave points      13.485419
28           worst symmetry       1.298861
29  worst fractal dimension       0.231522

In [38]:
feature_scores = feature_scores.sort_values(
    by="Chi2 Score",
    ascending=False
)

print(feature_scores)

                    Feature     Chi2 Score
23               worst area  112598.431564
3                 mean area   53991.655924
13               area error    8758.504705
22          worst perimeter    3665.035416
2            mean perimeter    2011.102864
20             worst radius     491.689157
0               mean radius     266.104917
12          perimeter error     250.571896
21            worst texture     174.449400
1              mean texture      93.897508
26          worst concavity      39.516915
10             radius error      34.675247
6            mean concavity      19.712354
25        worst compactness      19.314922
27     worst concave points      13.485419
7       mean concave points      10.544035
5          mean compactness       5.403075
28           worst symmetry       1.298861
16          concavity error       1.044718
15        compactness error       0.613785
24         worst smoothness       0.397366
17     concave points error       0.305232
8             mean symmetry       0.257380
29  worst fractal dimension       0.231522
4           mean smoothness       0.149899
11            texture error       0.009794
19  fractal dimension error       0.006371
14         smoothness error       0.003266
18           symmetry error       0.000080
9    mean fractal dimension       0.000074

4. ANOVA

In [39]:
from sklearn.feature_selection import f_classif

In [40]:
data = load_breast_cancer()

In [41]:
X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = data.target

In [42]:
print(X.shape)

(569, 30)

In [43]:
selector = SelectKBest(
    score_func=f_classif,
    k=10
)

In [44]:
X_new = selector.fit_transform(X, y)

In [45]:
print("Original Shape :", X.shape)
print("New Shape :", X_new.shape)

Original Shape : (569, 30)
New Shape : (569, 10)

5. Mutual Information

In [46]:
from sklearn.feature_selection import mutual_info_classif

In [47]:
data = load_breast_cancer()

In [48]:
X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = data.target

In [49]:
print(X.shape)

(569, 30)

In [50]:
selector = SelectKBest(
    score_func=mutual_info_classif,
    k=10
)

In [51]:
X_new = selector.fit_transform(X, y)

In [52]:
print(X.shape)
print(X_new.shape)

(569, 30)
(569, 10)

In [53]:
selected_features = X.columns[
    selector.get_support()
]

print(selected_features)

Index(['mean radius', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points', 'area error', 'worst radius', 'worst perimeter',
       'worst area', 'worst concave points'],
      dtype='str')

In [54]:
X_new = pd.DataFrame(
    X_new,
    columns=selected_features
)

X_new.head()

,mean radius,mean perimeter,mean area,mean concavity,mean concave points,area error,worst radius,worst perimeter,worst area,worst concave points
0,17.99,122.80,1001.0,0.3001,0.14710,153.40,25.38,184.60,2019.0,0.2654
1,20.57,132.90,1326.0,0.0869,0.07017,74.08,24.99,158.80,1956.0,0.1860
2,19.69,130.00,1203.0,0.1974,0.12790,94.03,23.57,152.50,1709.0,0.2430
3,11.42,77.58,386.1,0.2414,0.10520,27.23,14.91,98.87,567.7,0.2575
4,20.29,135.10,1297.0,0.1980,0.10430,94.44,22.54,152.20,1575.0,0.1625

In [55]:
print(selector.scores_)

[0.36479367 0.09808895 0.40214537 0.35986524 0.07840657 0.21624549
 0.37341071 0.43859619 0.07019995 0.00859121 0.24994402 0.
 0.27411105 0.33873466 0.0174435  0.07451554 0.11636421 0.1272208
 0.0133116  0.03971725 0.45533547 0.12328776 0.47563026 0.46389976
 0.1053078  0.22561145 0.31651891 0.43730624 0.09156457 0.07003302]

In [56]:
feature_scores = pd.DataFrame({
    "Feature": X.columns,
    "MI Score": selector.scores_
})

feature_scores

                    Feature  MI Score
0               mean radius  0.364794
1              mean texture  0.098089
2            mean perimeter  0.402145
3                 mean area  0.359865
4           mean smoothness  0.078407
5          mean compactness  0.216245
6            mean concavity  0.373411
7       mean concave points  0.438596
8             mean symmetry  0.070200
9    mean fractal dimension  0.008591
10             radius error  0.249944
11            texture error  0.000000
12          perimeter error  0.274111
13               area error  0.338735
14         smoothness error  0.017444
15        compactness error  0.074516
16          concavity error  0.116364
17     concave points error  0.127221
18           symmetry error  0.013312
19  fractal dimension error  0.039717
20             worst radius  0.455335
21            worst texture  0.123288
22          worst perimeter  0.475630
23               worst area  0.463900
24         worst smoothness  0.105308
25        worst compactness  0.225611
26          worst concavity  0.316519
27     worst concave points  0.437306
28           worst symmetry  0.091565
29  worst fractal dimension  0.070033