In [1]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

In [8]:
ipl = pd.read_csv('Dataset/ipl_deliveries - ipl_deliveries.csv')

In [9]:
ipl

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [13]:
top50= ipl.groupby('batter')['batsman_run'].sum().sort_values(ascending=False).head(50)

In [14]:
top50

batter
V Kohli           6634
S Dhawan          6244
DA Warner         5883
RG Sharma         5881
SK Raina          5536
AB de Villiers    5181
CH Gayle          4997
MS Dhoni          4978
RV Uthappa        4954
KD Karthik        4377
G Gambhir         4217
AT Rayudu         4190
AM Rahane         4074
KL Rahul          3895
SR Watson         3880
MK Pandey         3657
SV Samson         3526
KA Pollard        3437
F du Plessis      3403
YK Pathan         3222
BB McCullum       2882
RR Pant           2851
PA Patel          2848
JC Buttler        2832
SS Iyer           2780
Q de Kock         2767
Yuvraj Singh      2754
V Sehwag          2728
SA Yadav          2644
M Vijay           2619
RA Jadeja         2502
SPD Smith         2495
SE Marsh          2489
DA Miller         2455
WP Saha           2427
JH Kallis         2427
DR Smith          2385
MA Agarwal        2335
SR Tendulkar      2334
GJ Maxwell        2320
N Rana            2181
R Dravid          2174
KS Williamson     2105
AJ Finch          2092
AC Gilchrist      2069
AD Russell        2039
JP Duminy         2029
MEK Hussey        1977
HH Pandya         1972
Shubman Gill      1900
Name: batsman_run, dtype: int64

In [17]:
new_ipl= ipl[ipl['batter'].isin(top50)]
new_ipl

Empty DataFrame
Columns: [ID, Team, innings, overs, ballnumber, batter, bowler, non-striker, extra_type, batsman_run, extras_run, total_run, non_boundary, isWicketDelivery, player_out, kind, fielders_involved, BattingTeam, BowlingTeam]
Index: []