In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [57]:
df= pd.read_csv("medical_data.csv")

In [58]:
df

     age  sex     BMI  children smoker  region      charges
0     19    1  27.900         0      1       3  16884.92400
1     18    2  33.770         1      0       4   1725.55230
2     28    2  33.000         3      0       4   4449.46200
3     33    2  22.705         0      0       1  21984.47061
4     32    2  28.880         0      0       1   3866.85520
...   ..  ...     ...       ...    ...     ...          ...
2767  47    1  45.320         1      0       4   8569.86180
2768  21    1  34.600         0      0       3   2020.17700
2769  19    2  26.030         1      1       1  16450.89470
2770  23    2  18.715         0      0       1  21595.38229
2771  54    2  31.600         0      0       3   9850.43200

[2772 rows x 7 columns]

In [59]:
df.shape

(2772, 7)

In [60]:
df.describe()

               sex          BMI     children       region       charges
count  2772.000000  2772.000000  2772.000000  2772.000000   2772.000000
mean      1.507215    30.701349     1.101732     2.559885  13261.369959
std       0.500038     6.129449     1.214806     1.130761  12151.768945
min       1.000000    15.960000     0.000000     1.000000   1121.873900
25%       1.000000    26.220000     0.000000     2.000000   4687.797000
50%       2.000000    30.447500     1.000000     3.000000   9333.014350
75%       2.000000    34.770000     2.000000     4.000000  16577.779500
max       2.000000    53.130000     5.000000     4.000000  63770.428010

In [61]:
df.dtypes

age          object
sex           int64
BMI         float64
children      int64
smoker       object
region        int64
charges     float64
dtype: object

In [62]:
print(df['age'].unique())

['19' '18' '28' '33' '32' '31' '46' '37' '60' '25' '62' '23' '56' '27'
 '52' '30' '34' '59' '63' '55' '22' '26' '35' '24' '41' '38' '36' '21'
 '48' '40' '58' '53' '43' '64' '20' '61' '44' '57' '29' '45' '54' '49'
 '47' '51' '42' '50' '39' '?']

In [63]:
df['smoker'].unique()

array(['1', '0', '?'], dtype=object)

In [64]:
df['smoker'] = df['smoker'].replace('?', np.nan)

In [65]:
df['age'] = df['age'].replace('?', np.nan)

In [66]:
df['age'] = df['age'].astype(float)
df['sex'] = df['sex'].astype(float)
df['children'] = df['children'].astype(float)
df['smoker'] = df['smoker'].astype(float)
df['region'] = df['region'].astype(float)

In [67]:
df.isnull().sum()

age         4
sex         0
BMI         0
children    0
smoker      7
region      0
charges     0
dtype: int64

In [68]:
df= df.dropna()

In [69]:
df.isnull().sum()

age         0
sex         0
BMI         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [71]:
df.shape

(2761, 7)

In [72]:
X= df.iloc[:, 0:-1]

In [73]:
X

       age  sex     BMI  children  smoker  region
0     19.0  1.0  27.900       0.0     1.0     3.0
1     18.0  2.0  33.770       1.0     0.0     4.0
2     28.0  2.0  33.000       3.0     0.0     4.0
3     33.0  2.0  22.705       0.0     0.0     1.0
4     32.0  2.0  28.880       0.0     0.0     1.0
...    ...  ...     ...       ...     ...     ...
2767  47.0  1.0  45.320       1.0     0.0     4.0
2768  21.0  1.0  34.600       0.0     0.0     3.0
2769  19.0  2.0  26.030       1.0     1.0     1.0
2770  23.0  2.0  18.715       0.0     0.0     1.0
2771  54.0  2.0  31.600       0.0     0.0     3.0

[2761 rows x 6 columns]

In [74]:
y= df.iloc[:,-1]

In [75]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
2767     8569.86180
2768     2020.17700
2769    16450.89470
2770    21595.38229
2771     9850.43200
Name: charges, Length: 2761, dtype: float64

In [76]:
print(X.shape)
print(y.shape)

(2761, 6)
(2761,)

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [78]:
print("X_train :", X_train.shape)
print("X_test :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test :", y_test.shape)

X_train : (2208, 6)
X_test : (553, 6)
y_train : (2208,)
y_test : (553,)

In [79]:
lr= LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [82]:
y_pred= lr.predict(X_test)

print("Intercept:", lr.intercept_)
print("Coefficients:", lr.coef_)
print("R² Score:", r2_score(y_test, y_pred))

Intercept: -12022.229016613486
Coefficients: [  260.69729968   112.30635076   329.68757142   509.7275058
 24147.03598504  -259.39232484]
R² Score: 0.7075749166784169