In [24]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [7]:
df= pd.read_csv('Housing.csv')

In [8]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [9]:
X = df[['area','bedrooms','bathrooms']]

In [10]:
y = df['price']

In [11]:
X

     area  bedrooms  bathrooms
0    7420         4          2
1    8960         4          4
2    9960         3          2
3    7500         4          2
4    7420         4          1
..    ...       ...        ...
540  3000         2          1
541  2400         3          1
542  3620         2          1
543  2910         3          1
544  3850         3          1

[545 rows x 3 columns]

In [12]:
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [13]:
X_train,X_test,y_train,y_test = train_test_split(
X,y,test_size=0.2,random_state=42)

In [14]:
X_train

     area  bedrooms  bathrooms
46   6000         3          2
93   7200         3          2
335  3816         2          1
412  2610         3          1
471  3750         3          1
..    ...       ...        ...
71   6000         4          2
106  5450         4          2
270  4500         3          2
435  4040         2          1
102  5500         3          2

[436 rows x 3 columns]

In [15]:
lr = LinearRegression()

In [17]:
lr.fit(X_train, y_train)

LinearRegression()

In [18]:
y_pred= lr.predict(X_test)

In [19]:
y_pred

array([6383168.05981192, 6230250.35140428, 3597885.28090091,
       4289730.8386382 , 3930445.60575177, 4883933.33918115,
       5505773.16533075, 6068793.48103629, 3321512.02483442,
       3495157.72744705, 8731338.12527607, 3561265.8244721 ,
       3487335.97847431, 3633344.35548029, 3933900.2714526 ,
       6661080.95290716, 2893133.47793136, 4635197.40872131,
       4583377.42320885, 4274999.75826381, 4296640.17003986,
       4920207.32903988, 3462807.85199841, 3875170.95453847,
       5412497.19140831, 7425564.68389184, 3269692.03932195,
       5021117.35611339, 7122556.71331971, 3238600.04801447,
       5366583.9261965 , 3640253.68688195, 6057517.06636272,
       4847659.34932243, 4572198.51082701, 5573863.86824637,
       4167435.67282878, 4021179.33154444, 3764621.65211187,
       5307730.62714319, 5319221.21748587, 3456243.98716683,
       6202613.02579763, 4013357.58257171, 4534099.68582614,
       4235271.10270425, 6057517.06636272, 4525560.52386579,
       4983206.22693419, 3238600.04801447, 6567080.25723531,
       3238600.04801447, 4886475.58731091, 4116997.55359665,
       4180093.95378268, 3567705.7071645 , 5971150.42384195,
       3391517.75642211, 5150855.01571622, 3514973.30408096,
       4723103.68827085, 4722288.7729915 , 4427005.04910038,
       3915714.52537737, 4414098.80386812, 3861352.29173514,
       5904599.35795509, 3598797.69847198, 5824514.82737829,
       4531557.43769638, 4969297.37060092, 4759565.37395123,
       5104119.52646327, 7612116.63173672, 3129432.61186821,
       5816602.88487562, 3816441.63762434, 3865621.87271532,
       4635197.40872131, 4393370.80966313, 6542082.68205015,
       3971901.59416174, 5884783.78132117, 4866660.010677  ,
       3149691.15736393, 7466018.06120081, 3529704.38445536,
       3754257.65500938, 6908277.24633825, 7840034.37446164,
       3940907.10514598, 5343403.87739169, 4084993.1447181 ,
       3740438.99220605, 9091535.77573357, 4200821.94798766,
       4935974.80912452, 5988423.7523461 , 4462464.12367976,
       6624994.6588701 , 3681709.67529193, 5573863.86824637,
       3588433.70136949, 6547076.98477974, 4995395.05917882,
       5316678.96935611, 6417714.71682023, 6057517.06636272,
       6092063.72337104])

In [20]:
print(r2_score(y_test,y_pred))

0.45592991188724463

In [21]:
lr.coef_

array([3.45466570e+02, 3.60197650e+05, 1.42231966e+06])

In [22]:
lr.intercept_

np.float64(59485.379208717495)

In [25]:
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("R2 Score :", r2_score(y_test, y_pred))

MAE : 1265275.6699454375
MSE : 2750040479309.052
R2 Score : 0.45592991188724463