In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [25]:
housing = fetch_california_housing()

X = housing.data
y = housing.target

print(X.shape)

(20640, 8)

In [26]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [27]:
print(X.shape)
print(y.shape)

(20640, 8)
(20640,)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [30]:
#Linear Regression without GD

start = time.time()

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

end = time.time()

pred_lr = lr.predict(X_test_scaled)

print("Training Time:", end - start)
print("R2:", r2_score(y_test, pred_lr))
print("MSE:", mean_squared_error(y_test, pred_lr))

Training Time: 0.00926065444946289
R2: 0.575787706032451
MSE: 0.5558915986952442

In [31]:
#SGD

start = time.time()

sgd = SGDRegressor(
    max_iter=5000,
    eta0=0.01,
    learning_rate="constant",
    random_state=42
)

sgd.fit(X_train_scaled, y_train)
end = time.time()

pred_sgd = sgd.predict(X_test_scaled)

print("Training Time:", end - start)
print("R2:", r2_score(y_test, pred_sgd))
print("MSE:", mean_squared_error(y_test, pred_sgd))

Training Time: 0.0207517147064209
R2: -4.557481488386458e+20
MSE: 5.972164660548314e+20

In [32]:
comparison = pd.DataFrame({
    "Feature": housing.feature_names,
    "LinearRegression": lr.coef_,
    "SGDRegressor": sgd.coef_
})

comparison

      Feature  LinearRegression  SGDRegressor
0      MedInc          0.854383  9.853643e+08
1    HouseAge          0.122546 -3.274194e+09
2    AveRooms         -0.294410 -3.977309e+09
3   AveBedrms          0.339259  6.100570e+09
4  Population         -0.002308 -6.713868e+09
5    AveOccup         -0.040829  1.604235e+11
6    Latitude         -0.896929 -1.555110e+09
7   Longitude         -0.869842 -2.964012e+09

In [33]:
comparison_pred = pd.DataFrame({
    "Actual": y_test[:10],
    "LinearRegression": pred_lr[:10],
    "SGD": pred_sgd[:10]
})

comparison_pred

    Actual  LinearRegression           SGD
0  0.47700          0.719123  1.321859e+10
1  0.45800          1.764017 -2.921667e+09
2  5.00001          2.709659 -2.079211e+10
3  2.18600          2.838926  7.101813e+09
4  2.78000          2.604657 -3.609379e+09
5  1.58700          2.011754 -5.120948e+09
6  1.98200          2.645500  2.425692e+09
7  1.57500          2.168755  1.074685e+10
8  3.40000          2.740746 -2.295069e+09
9  4.46600          3.915615 -5.588292e+09