In [ ]:
'''
Data Analysis Include-
i) - Data Gathering
ii) - Data Cleaning
iii) - EDA

'''

In [4]:
import pandas as pd

In [6]:
df= pd.read_csv("DATASET/aug_train.csv")

In [7]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [9]:
import requests

In [14]:
Response= requests.get(url = f"https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1")

In [15]:
Response

In [19]:
pd.DataFrame(Response.json()['results'])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,48.2516,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.719,30190
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",43.7797,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.686,22803
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,30.9353,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,False,False,8.572,13824
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,31.8966,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.567,17356
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,22.4208,/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg,1957-04-10,False,False,8.558,9912
5,False,/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg,"[16, 10751, 14]",129,Spirited Away,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",35.0613,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,False,False,8.533,18197
6,False,/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg,"[28, 80, 53]",155,The Dark Knight,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,38.2205,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,False,False,8.528,35565
7,False,/6N5d02quKqMKqvTpOdFmBDy9scY.jpg,"[35, 18, 10749]",19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",14.2059,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,False,False,8.513,4575
8,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,The Green Mile,en,The Green Mile,A supernatural tale set on death row in a Sout...,27.6507,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,False,False,8.504,19131
9,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,70.7293,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,False,False,8.496,26370
10,False,/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg,"[35, 53, 18]",496243,Parasite,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",32.4436,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,False,False,8.494,20481
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,Pulp Fiction,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",32.6636,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,False,False,8.484,30053
12,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,Your Name.,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,25.7912,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,False,False,8.476,12450
13,False,/2ssWTSVklAEc98frZUQhgtGHx7s.jpg,"[12, 18, 878]",157336,Interstellar,en,Interstellar,The adventures of a group of explorers who mak...,90.8739,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg,2014-11-05,False,False,8.471,39490
14,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,¿Quieres ser mi hijo?,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",15.4353,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,False,False,8.469,321
15,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,"The Good, the Bad and the Ugly",it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,24.3542,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-23,False,False,8.469,9570
16,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,"[35, 18, 10749]",13,Forrest Gump,en,Forrest Gump,A man with a low IQ has accomplished great thi...,30.0113,/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg,1994-06-23,False,False,8.500,29590
17,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,GoodFellas,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",25.2848,/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg,1990-09-12,False,False,8.453,14241
18,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,Seven Samurai,ja,七人の侍,A samurai answers a village's request for prot...,36.3665,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,False,False,8.449,4194
19,False,/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg,"[16, 18, 10752]",12477,Grave of the Fireflies,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0148,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,False,False,8.441,6475

In [23]:
df = pd.DataFrame(Response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [24]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,48.2516,8.719,30190
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,43.7797,8.686,22803
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,30.9353,8.572,13824
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,31.8966,8.567,17356
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,22.4208,8.558,9912

In [26]:
df =pd.DataFrame()

In [ ]:
for i in range(1,429):
    response= requests.get(url = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}".format(i))
    temp_df= pd.DataFrame(Response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df= df.append(temp_df, ignore_index=True)

In [38]:
df.shape

(0, 0)

In [39]:
df.to_csv('movies.csv')